### ISSUE TITLE
Uncaught SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by tuyendev** [robrotheram/taiga-contrib-openid-auth#11]
I tried to install taiga on my host server(not docker). Everything works perfectly util i try to installl openid_auth plugin. 
In console, it said
```
Uncaught SyntaxError: Unexpected token '<'
libs.js:1 Uncaught Error: [$injector:modulerr] Failed to instantiate module taiga due to:
Error: [$injector:modulerr] Failed to instantiate module taigaContrib.openidAuth due to:
Error: [$injector:nomod] Module 'taigaContrib.openidAuth' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.
http://errors.angularjs.org/1.5.10/$injector/nomod?p0=taigaContrib.openidAuth
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:207063
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:218290
    at n (https://taiga.private-host/v-1613740088579/js/libs.js:1:217992)
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:218261
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:230975
    at ge (https://taiga.private-host/v-1613740088579/js/libs.js:1:208051)
    at n (https://taiga.private-host/v-1613740088579/js/libs.js:1:230920)
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:230991
    at ge (https://taiga.private-host/v-1613740088579/js/libs.js:1:208051)
    at n (https://taiga.private-host/v-1613740088579/js/libs.js:1:230920)
http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=taigaContrib.openidAuth&p1=Error%3A%20%5B%24injector%3Anomod%5D%20Module%20'taigaContrib.openidAuth'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3DtaigaContrib.openidAuth%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A207063%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A218290%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A217992)%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A218261%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230975%0A%20%20%20%20at%20ge%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A208051)%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230920)%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230991%0A%20%20%20%20at%20ge%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A208051)%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230920)
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:207063
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:231233
    at ge (https://taiga.private-host/v-1613740088579/js/libs.js:1:208051)
    at n (https://taiga.private-host/v-1613740088579/js/libs.js:1:230920)
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:230991
    at ge (https://taiga.private-host/v-1613740088579/js/libs.js:1:208051)
    at n (https://taiga.private-host/v-1613740088579/js/libs.js:1:230920)
    at qt (https://taiga.private-host/v-1613740088579/js/libs.js:1:231431)
    at i (https://taiga.private-host/v-1613740088579/js/libs.js:1:216401)
    at Object.se [as bootstrap] (https://taiga.private-host/v-1613740088579/js/libs.js:1:216709)
http://errors.angularjs.org/1.5.10/$injector/modulerr?p0=taiga&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20taigaContrib.openidAuth%20due%20to%3A%0AError%3A%20%5B%24injector%3Anomod%5D%20Module%20'taigaContrib.openidAuth'%20is%20not%20available!%20You%20either%20misspelled%20the%20module%20name%20or%20forgot%20to%20load%20it.%20If%20registering%20a%20module%20ensure%20that%20you%20specify%20the%20dependencies%20as%20the%20second%20argument.%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fnomod%3Fp0%3DtaigaContrib.openidAuth%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A207063%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A218290%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A217992)%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A218261%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230975%0A%20%20%20%20at%20ge%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A208051)%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230920)%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230991%0A%20%20%20%20at%20ge%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A208051)%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230920)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.5.10%2F%24injector%2Fmodulerr%3Fp0%3DtaigaContrib.openidAuth%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520Module%2520'taigaContrib.openidAuth'%2520is%2520not%2520available!%2520You%2520either%2520misspelled%2520the%2520module%2520name%2520or%2520forgot%2520to%2520load%2520it.%2520If%2520registering%2520a%2520module%2520ensure%2520that%2520you%2520specify%2520the%2520dependencies%2520as%2520the%2520second%2520argument.%250Ahttp%253A%252F%252Ferrors.angularjs.org%252F1.5.10%252F%2524injector%252Fnomod%253Fp0%253DtaigaContrib.openidAuth%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A207063%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A218290%250A%2520%2520%2520%2520at%2520n%2520(https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A217992)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A218261%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A230975%250A%2520%2520%2520%2520at%2520ge%2520(https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A208051)%250A%2520%2520%2520%2520at%2520n%2520(https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A230920)%250A%2520%2520%2520%2520at%2520https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A230991%250A%2520%2520%2520%2520at%2520ge%2520(https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A208051)%250A%2520%2520%2520%2520at%2520n%2520(https%253A%252F%252Ftaiga.private-host%252Fv-1613740088579%252Fjs%252Flibs.js%253A1%253A230920)%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A207063%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A231233%0A%20%20%20%20at%20ge%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A208051)%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230920)%0A%20%20%20%20at%20https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230991%0A%20%20%20%20at%20ge%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A208051)%0A%20%20%20%20at%20n%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A230920)%0A%20%20%20%20at%20qt%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A231431)%0A%20%20%20%20at%20i%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A216401)%0A%20%20%20%20at%20Object.se%20%5Bas%20bootstrap%5D%20(https%3A%2F%2Ftaiga.private-host%2Fv-1613740088579%2Fjs%2Flibs.js%3A1%3A216709)
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:207063
    at https://taiga.private-host/v-1613740088579/js/libs.js:1:231233
    at ge (https://taiga.private-host/v-1613740088579/js/libs.js:1:208051)
    at n (https://taiga.private-host/v-1613740088579/js/libs.js:1:230920)
    at qt (https://taiga.private-host/v-1613740088579/js/libs.js:1:231431)
    at i (https://taiga.private-host/v-1613740088579/js/libs.js:1:216401)
    at Object.se [as bootstrap] (https://taiga.private-host/v-1613740088579/js/libs.js:1:216709)
    at Object.<anonymous> (https://taiga.private-host/v-1613740088579/js/app-loader.js:1:1855)
    at Object.<anonymous> (https://taiga.private-host/v-1613740088579/js/libs.js:1:28262)
    at i (https://taiga.private-host/v-1613740088579/js/libs.js:1:26926)
```
What I have tried:
- I tried to create docker version , then copy all taiga-front resource in container(/usr/share/nginx/html) to real host => the errors still happend
- I tried to use gitlab-auth plugin to make sure I don't do anything worng with conf.json. It worked but when I switched back to openid-auth, still the same
Do you have any suggestion? 

Thank you so much

I'm using: 
-  taiga version 6
- ubuntu 20.04

**Comment by tuyendev** [comment]
I found the reason that related with caching on cloudflare. Now it works :)
